
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#configurando rotas
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cambio-service
          uri: lb://cambio-service
          predicates:
            - Path=/cambio-service/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
        - id: book-service
          uri: lb://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  #logs
  sleuth:
    sampler:
      probability: 1.0