
server:
  port: 8765
spring:
  profiles:
    active: dev
  application:
    name: api-gateway
#cloud gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true