version: '3.4'

services:

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    restart: always
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - erudio-network

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - erudio-network

  naming-server:
    image: viniciushora/naming-server:latest
    ports:
      - 8761:8761
    networks:
      - erudio-network
  
  api-gateway:
    image: viniciushora/api-gateway:latest
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      ZIPKIN.BASE-URL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - erudio-network 

  #db_cambio
  db_cambio:
      image: postgres:alpine3.16 
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: cambio_service
        TZ: America/Sao_Paulo
        POSTGRES_PORT: 5432
      # ports:
      #   - "35434:5432"
      restart: always
      networks:
        - erudio-network
 
  cambio-service:
    image: viniciushora/cambio-service:latest
    restart: always
    ports:
      - 4103:4103
    depends_on:
      - naming-server
      - rabbit-mq
      - db_cambio
    environment:
      SPRING.APPLICATION.NAME: cambio-service
      TZ: America/Sao_Paulo
      ZIPKIN.BASE-URL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      #banco de dados em oura rede - outro docoker compose
      DB_URL: jdbc:postgresql://db_cambio:5432/cambio_service
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL_FLYWAY: jdbc:postgresql://db_cambio:5432/cambio_service
      #rabbit-mq
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - erudio-network
      # - docker_local
  
  #db_cambio
  db_book:
      image: postgres:alpine3.16 
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: book_service
        TZ: America/Sao_Paulo
      #   POSTGRES_PORT: 5433
      # ports:
      #   - 35433:5433
      restart: always
      networks:
        - db-book-network
  book-service:
    image: viniciushora/book-service:latest
    restart: always
    ports:
      - 4104:4104
    depends_on:
      - naming-server
      - rabbit-mq
      - db_book
    environment:
      SPRING.APPLICATION.NAME: book-service
      TZ: America/Sao_Paulo
      ZIPKIN.BASE-URL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      #banco de dados em oura rede - outro docoker compose
      DB_URL: jdbc:postgresql://db_book:5432/book_service
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL_FLYWAY: jdbc:postgresql://db_book:5432/book_service
      #rabbit-mq
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - erudio-network
      - db-book-network
      # - docker_local
 
    
networks:
  erudio-network:
    driver: bridge
  db-book-network:
    driver: bridge
  # docker_local:
  #   external: true
    