version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - erudio-network

  naming-server:
    image: viniciushora/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - erudio-network
  
  api-gateway:
    image: viniciushora/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      ZIPKIN.BASE-URL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - erudio-network 
  
  cambio-service:
    image: viniciushora/cambio-service
    restart: always
    build:
      context: .
      dockerfile: ../cambio-service/Dockerfile
    ports:
      - 4103:4103
    depends_on:
      - naming-server
    environment:
      SPRING.APPLICATION.NAME: cambio-service
      TZ: America/Sao_Paulo
      ZIPKIN.BASE-URL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      #banco de dados em oura rede - outro docoker compose
      DB_URL: jdbc:postgresql://database:35432/cambio_service
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL_FLYWAY: jdbc:postgresql://database:35432/cambio_service
    networks:
      - erudio-network
      - docker_local
 
    
networks:
  erudio-network:
    driver: bridge
  docker_local:
    external: true
    