server:
  port: 8888
spring:
  application:
    name: erudio-config-server
#configuração de cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vinicius-hora/erudio-confg-server
          search-paths:
            - 'greeting-service*'
        #password:
        #username:
        default-label: main
